apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongo
    spec:
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-pvc
      containers:
      - name: mongodb-container
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: pankaj
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: pankaj@9201
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db

---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - name: http
    port: 27017  #<service port>
    targetPort: 27017   #<container port>
    protocol: TCP