apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: java-rc
  namespace: prod
spec:
  replicas: 4
  selector:
    matchLabels:
      app: java
  template:  #POD TEMPLATE
    metadata:
      name: java-pod
      namespace: prod 
      labels:
        app: java
    spec:
      containers:
      - name: java-cont
        image: 8983795200/java-web-app:1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: java-svc-np
  namespace: prod
spec:
  type: LoadBalancer
  selector:
    app: java
  ports:
  - name: java-port
    port: 8080   # service port
    targetPort: 8080  # container port
    protocol: TCP
