apiVersion: v1
kind: LimitRange
metadata:
  name: test-limit-range
  namespace: project-a
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 300m
      memory: 512Mi
    max:
      cpu: 1
      memory: 4Gi
    min:
      cpu: 200m
      memory: 256Mi
    type: Container