apiVersion: v1
kind: ResourceQuota
metadata: 
  name: project-a-quota
  namespace: project-a
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: 2