apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-java
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  minReadySeconds: 90
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      name: java-pod
      labels:
        app: java
    spec:
      containers:
      - name: java-container
        image: 8983795200/java-web-app:1
        ports:
        - containerPort: 8080