apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  containers:
  - name: httpd-container
    image: httpd
    ports:
    - containerPort: 80
  - name: tomcat-container
    image: tomcat
    ports:
    - containerPort: 8080