apiVersion: v1
kind: Pod
metadata:
  name: java-pod
  namespace: pankaj-1
  labels:
    app: java
spec:
  containers:
  - name: java-container
    image: 8983795200/java-web-app:1
    ports:
    - containerPort: 8080